In [ ]:
#EXERCICE 4

import numpy as np

array = np.array([100,200,300,400,500,600])

print(f"Matriz Original: {array}\n")

array_1, array_2 = np.split(array, 2)

print(f"Matriz Redimencionada: \n\n{array_1}\n{array_2}\n")

array_2 = np.append(array_2, [700])

print(f"Matriz Modificada: \n\n{array_1}\n{array_2}")

Matriz Original: [100 200 300 400 500 600]

Matriz Redimencionada: 

[100 200 300]
[400 500 600]
Matriz Modificada: 

[100 200 300]
[400 500 600 700]


In [13]:
#EXERCICE 3

import numpy as np
array_original = np.array([10,20,30,40,50])
array_copia = np.copy(array_original)

array_copia[2] = 60
print(array_original)
print(array_copia)

[10 20 30 40 50]
[10 20 60 40 50]


In [ ]:
#EXERCICE 2

import numpy as np

matriz_1 = np.array([1,2,3])
matriz_2 = np.array([4,5,6])

result = np.concatenate((matriz_1, matriz_2))

print(result)

print(result[1:5])

[1 2 3 4 5 6]
[2 3 4 5]


In [ ]:
#EXERCICE 1

import numpy as np

# matriz = np.array([10,20,3,20,1,3,2])

matriz = np.array([0,1,2,3,4,5,6,7,8,9,10,11])

matriz = np.resize(matriz, (3,4))

print(matriz)

print(matriz[1])
print(matriz[2, 3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]
11
